config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos do
    collection do
      get :my_videos
    end

    member do
      get :play
    end
  end

  root to: 'videos#my_videos'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
    validates :name, presence: true
    validates :url, presence: true
    validates :user, presence: true
    validate :verify_extension
    validate :url_valid?

    belongs_to :user
    
    def verify_extension
        if self.url
            unless self.url.end_with? ".m3u8"
                errors.add(:url, { url: "Deve-se ter a extensão .m3u8" })
            end
        end
    end

    def url_valid?
        if self.url
            unless URI.regexp.match?(self.url)
                errors.add(:url, {url: "URL inválida"})
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404

    def render_404
        redirect_to videos_path, notice: "Video não encontrado"
    end
 
    def set_locale
        session[:locale] = params[:locale] if params[:locale].present?
        I18n.locale = session[:locale] || I18n.default_locale
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: [:show, :edit, :update, :destroy, :play]
  before_action :authorized?, only: [:edit, :destroy, :show]

  def index
    @q = Video.ransack(params[:q])
    @videos = @q.result(distinct: true).order("score DESC").paginate(page: params[:page], per_page: 7)
  end

  def my_videos
    @videos = current_user.videos.order("score DESC").paginate(page: params[:page], per_page: 7)
  end

  def show
  end

  def play
    @video.update_attribute(:score, @video.score + 1)
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = current_user.videos.new(video_params)
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: t('create_ok') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: t('update_ok') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to my_videos_videos_url, notice: t('destroy_ok') }
    end
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end

  def authorized?
    unless @video.user == current_user
      redirect_to videos_url, alert: t('permited_not')
    end
  end

  def video_params
    params.require(:video).permit(:name, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_navbar.html.erb
<div class="topnav">
  <a href=<%=videos_path%>> <%=t("all")%> </a>
  <a href= <%=my_videos_videos_path%> ><%=t("my_videos")%></a>
  <a href="<%= request.path %>?locale=en">
    <span class="flag-icon flag-icon-us"></span>
  </a>
  <a href="<%= request.path %>?locale=pt-BR">
    <span class="flag-icon flag-icon-br"></span>
  </a>
  <div class="topnav-right">
    <%= link_to(t("sign_out"), destroy_user_session_path, method: :delete, title: t("sign_out")) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetshowVideo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <div class="col-md-12" style="background-color: #007fff;">
      <%= render 'layouts/navbar' %>
    </div>
    <div class="col-md-12" style="background-color: white;">
      <%= yield %>
    <div>
    <script src="https://kit.fontawesome.com/d196caa582.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= video.errors.count %> <%= t("error") %> <%=t('not_save')%></h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="bs-callout bs-callout-primary">

    <div class="form-group col-md-12">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group col-md-12">
      <%= form.label :url %>
      <%= form.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class="actions pull-right col-md-6">
    <%= link_to t('my_videos'), my_videos_videos_path, class: 'btn btn-default' %>
    <%= form.submit t('helpers.submit')%>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1><%= translate 'actions.edit'%> <%= @video.model_name.human %> </h1>
<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %><p>

<h1><%=t('all')%></h1> <br>

<form>
  <div>
      <%= search_form_for @q, url: videos_path, remote: true do |f| %>
          <div class="col col-md-6" style="display: inline-block">
            <%= f.search_field :name_cont,  class: "form-control", 
              placeholder: @videos.human_attribute_name("name"),
              title: @videos.human_attribute_name("name") %>
          </div>
          <div class="col col-md-3" style="display: inline-block">
            <%= f.submit t("search"), class: "btn btn-primary" %>
          </div> 
      <% end %>
  </div>
</form> <br><br>

<table class="table table-striped table-hover">
  <thead class="thead-light">
    <tr>
      <th><%=@videos.human_attribute_name("name")%></th>
      <th><%=@videos.human_attribute_name("score")%></th>
      <th><%= t("play") %></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <td><%= video.score %></td>
        <td><%= link_to '', play_video_path(video), class: "fas fa-play-circle fa-2x", title: t("play") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @videos %> <br>
<%= page_entries_info @videos %>

app/views/videos/my_videos.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t("my_videos")%></h1> <br>

<table class="table table-striped table-hover">
  <thead class="thead-light">
    <tr>
      <th><%=@videos.human_attribute_name("name")%></th>
      <th><%=@videos.human_attribute_name("url")%></th>
      <th><%=@videos.human_attribute_name("score")%></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.name, video %></td>
        <td><%= video.url %></td>
        <td><%= video.score %></td>
        <td><%= link_to '', edit_video_path(video), class: 'btn btn-outline-primary fas fa-edit fa-sm', title: t('actions.edit') %></td>
        <td><%= link_to '', video, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-outline-danger fas fa-trash-alt fa-sm', title: t('actions.destroy') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @videos %> <br>
<%= page_entries_info @videos %>
<br><br>
<%= link_to '', new_video_path, class: 'btn btn-outline-success fa fa-plus', title: t('actions.new') %>

app/views/videos/new.html.erb
<h1><%= translate 'actions.new'%> <%= @video.model_name.human %> </h1>

<%= render 'form', video: @video %>

app/views/videos/play.html.erb
<head>
  <link href="//vjs.zencdn.net/7.3.0/video-js.min.css" rel="stylesheet">
  <script src="//vjs.zencdn.net/7.3.0/video.min.js"></script>
</head>

<h5><%= @video.name %> </h5>
<h6> <%= @video.score %> <%=Video.human_attribute_name("score")%>  </h6>
<video id="my-video" class="video-js" controls preload="auto" autoplay="true" width="640" height="264" data-setup="{}">
    <source src=<%=@video.url%> type="application/x-mpegURL">
    <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
</video> <br> 

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= translate 'activerecord.attributes.video.name'%>:</strong>
  <%= @video.name %>
</p>

<p>
  <strong><%= translate 'activerecord.attributes.video.url'%>:</strong>
  <%= @video.url %>
</p>

<p>
  <strong><%= translate 'activerecord.attributes.video.score'%>:</strong>
  <%= @video.score %>
</p>

<%= link_to t('actions.edit'), edit_video_path(@video) %> |
<%= link_to t('my_videos'), my_videos_videos_path %>